#!/usr/bin/env bash
# Synthetic regression test for the stop-hook round-skip bug (issue #2).
#
# Drives setup through the real start-loop.sh + drafting->reviewing
# transition so the runner is generated by write_runner_script.
#
# Usage (from repo root):
#   bash tests/round-skip-regression.sh
#
# Exit 0 on PASS, non-zero on FAIL.
#
# This test must PASS on the patched script and FAIL on the unpatched
# script (specifically: unpatched fails at step 2 with round=2; patched
# stays at 1).

set -u

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PLUGIN_BASE="${PLUGIN_BASE:-$REPO_ROOT/plugins/claudex}"
HOOK="$PLUGIN_BASE/hooks/stop-hook.sh"
START_LOOP="$PLUGIN_BASE/scripts/start-loop.sh"
STATE_HELPERS="$PLUGIN_BASE/scripts/state-helpers.sh"

if [ ! -f "$HOOK" ]; then echo "FAIL: hook not at $HOOK"; exit 1; fi
if [ ! -f "$START_LOOP" ]; then echo "FAIL: start-loop not at $START_LOOP"; exit 1; fi

TMP=$(mktemp -d -t claudex-test-XXXXXX)
trap 'rm -rf "$TMP" 2>/dev/null' EXIT

cd "$TMP" || { echo "FAIL: cannot cd to $TMP"; exit 1; }

export CLAUDE_PLUGIN_ROOT="$PLUGIN_BASE"
# shellcheck source=/dev/null
source "$STATE_HELPERS"

fail() { echo "FAIL [$1]: $2"; exit 1; }
pass() { echo "PASS [$1]: $2"; }

read_round() {
  local f; f=$(claudex_find_active_loop 2>/dev/null)
  [ -z "$f" ] && { echo "?"; return; }
  claudex_state_read_field "$f" "round"
}
read_phase() {
  local f; f=$(claudex_find_active_loop 2>/dev/null)
  [ -z "$f" ] && { echo "?"; return; }
  claudex_state_read_field "$f" "phase"
}
read_signal() {
  local f; f=$(claudex_find_active_loop 2>/dev/null)
  [ -z "$f" ] && { echo "?"; return; }
  claudex_state_read_field "$f" "decision_signal"
}
fire_hook() { bash "$HOOK" <<< '{}' >/dev/null 2>&1 || true; }

bash "$START_LOOP" plan --rounds 2 "synthetic regression test" >/dev/null 2>&1 \
  || fail "setup" "start-loop.sh failed"
echo "test plan body" > PLAN.md

REVIEW_ID=$(basename "$(claudex_find_active_loop)" .state)
[ -n "$REVIEW_ID" ] || fail "setup" "no active loop after start-loop"
REVIEW_DIR=".claude/claudex/$REVIEW_ID"

# Step 1: drafting -> reviewing on first fire.
fire_hook
[ "$(read_phase)" = "reviewing" ] || fail "step1" "phase != reviewing"
[ "$(read_round)" = "1" ] || fail "step1" "round != 1"
pass "step1" "drafting -> reviewing, round=1"

# Step 2: re-fire with no sentinel. THIS IS THE BUG SURFACE.
fire_hook
ROUND_AFTER=$(read_round)
[ "$ROUND_AFTER" = "1" ] || fail "step2" "re-fire advanced round to $ROUND_AFTER without sentinel"
pass "step2" "re-fire kept round=1 (no sentinel)"

# Step 3: multiple consecutive re-fires.
fire_hook; fire_hook
[ "$(read_round)" = "1" ] || fail "step3" "re-fires advanced round to $(read_round)"
pass "step3" "3 consecutive re-fires kept round=1"

# Step 4: simulate round-1 success via sentinel.
mkdir -p "$REVIEW_DIR"
echo "x" > "$REVIEW_DIR/findings-round-1.md"
: > "$REVIEW_DIR/findings-round-1.md.ok"
fire_hook
[ "$(read_round)" = "2" ] || fail "step4" "sentinel fire did not advance to 2"
[ "$(read_phase)" = "reviewing" ] || fail "step4" "phase != reviewing"
pass "step4" "sentinel present -> advanced to round=2"

# Step 5: round-2 success -> max-rounds path.
echo "x" > "$REVIEW_DIR/findings-round-2.md"
: > "$REVIEW_DIR/findings-round-2.md.ok"
fire_hook
[ "$(read_round)" = "3" ] || fail "step5" "round != 3"
[ "$(read_phase)" = "summarizing" ] || fail "step5" "phase != summarizing"
[ "$(read_signal)" = "max-reached" ] || fail "step5" "signal != max-reached"
pass "step5" "round-2 sentinel -> round=3, summarizing, max-reached"

echo "ALL PASS"
exit 0
